language: elixir
matrix:
  include:
    - elixir: 1.4.5
      otp_release: 20.1
    - elixir: 1.5.3
      otp_release: 20.3
    - elixir: 1.6.6
      otp_release: 20.3
    - elixir: 1.7.4
      otp_release: 21.3
    - elixir: 1.8.2
      otp_release: 21.3
    - elixir: 1.8.2
      otp_release: 22.0
notifications:
  recipients:
    - andrew@andrewtimberlake.com
